import {  Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({
 
  subsets: ["latin"],
  weight: ['400', '500', '600', '700'],
  variable: "--font-poppins", 
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
      className={`${poppins.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        <Toaster position="top-center" reverseOrder={false} />
        </body>
        
    </html>
  );
}
